name: humantime

on: push

jobs:
  build:
    name: humantime build
    strategy:
      matrix:
        go-version: [1.18.x]
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v3

      - name: Set up Go 
        uses: actions/setup-go@v3
        with:
          go-version: 1.18
        id: go

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
          args: --timeout=5m

      - name: Build & Test
        run: |
          go mod tidy
          go test -v -race -count 1 -parallel 5 -coverprofile=profile.cov ./...
          go build -v -ldflags="-s -w" ./...
      
      - name: Install goveralls
        run: go install github.com/mattn/goveralls@latest
      
      - name: Send coverage
        env:
          COVERALLS_TOKEN: ${{ secrets.GH_SECRET_TOKEN }}
        run: goveralls -coverprofile=covprofile -service=github
